name: Package App with PyInstaller and Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ./
        spec: PlayStationDiscordRPC.spec

    - uses: actions/upload-artifact@v2
      with:
        name: PlayStationDiscordRPC
        path: src/dist/windows
