name: Package App with PyInstaller and Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ./
        spec: PlayStationDiscordRPC.spec

    - uses: actions/upload-artifact@v2
      with:
        name: PlayStationDiscordRPC
        path: ./dist/windows

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Release Version "
        files: |
          src/dist/windows/*.exe
